### ISSUE TITLE
Issue in POST Review

### ISSUE THREAD

**Issue by dodiya-divyarajsinh** [magento-hackathon/M2ReviewsAPI#1]
POST http://127.0.0.1/magento_2/index.php/rest/V1/reviews

CODE : 
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => "http://127.0.0.1/magento_2/index.php/rest/V1/reviews",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_POSTFIELDS => "{\n  \"data\": [\n    {\n      \"title\": \"Test\",\n      \"detail\": \"TEst\",\n      \"nickname\": \"Mr.TEST\",\n      \"customer_id\": \"2\",\n      \"rating\": \"4\",\n      \"product_id\": \"36\"\n    }\n  ]\n}",
  CURLOPT_HTTPHEADER => array(
    "authorization: Bearer lunrn2q22jmt17oxl43ymc1wdl8hjr3a",
    "cache-control: no-cache",
    "content-type: application/json"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}

RESULT : 
{
    "message": "%fieldName is a required field.",
    "parameters": {
        "fieldName": "review"
    }
}

**Comment by riconeitzel** [comment]
Obviously your request body is missing the field "review" … (don't know the extension but read the message and saw your request body).

**Comment by dodiya-divyarajsinh** [comment]
But this field is not define in data of web.xml where endpoint is define. if i pass this it will create log for error.

XML :

<route url="/V1/reviews" method="POST">
        <service class="MagentoHackathon\ReviewsApi\Api\ReviewsRepositoryInterface" method="post" />
        <resources>
            <resource ref="self"/>
        </resources>
        <data>
            <parameter name="title" force="true">%title%</parameter>
            <parameter name="detail" force="true">%detail%</parameter>
            <parameter name="nickname" force="true">%nickname%</parameter>
            <parameter name="customer_id" force="true">%customer_id%</parameter>
            <parameter name="rating" force="true">%rating%</parameter>
            <parameter name="product_id" force="true">%product_id%</parameter>
        </data>
    </route>

RESPONSE :

{
    "message": "Internal Error. Details are available in Magento log file. Report ID: webapi-59fc1ada47e90"
}

Next Exception: Report ID: webapi-59fc1ada47e90; Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null, query was: INSERT INTO `review_detail` (`title`, `detail`, `nickname`, `store_id`, `customer_id`, `review_id`) VALUES (?, ?, ?, ?, ?, ?) in /var/www/html/magento_2/vendor/magento/framework/Webapi/ErrorProcessor.php:195
Stack trace:
#0 /var/www/html/magento_2/vendor/magento/framework/Webapi/ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Zend_Db_Statement_Exception))
#1 /var/www/html/magento_2/vendor/magento/module-webapi/Controller/Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Zend_Db_Statement_Exception))
#2 /var/www/html/magento_2/var/generation/Magento/Webapi/Controller/Rest/Interceptor.php(37): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 /var/www/html/magento_2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 /var/www/html/magento_2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 /var/www/html/magento_2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []
